INSERT INTO school.courses (course_name) VALUES ('course1');
INSERT INTO school.groups (group_name) VALUES ('AA-11');
INSERT INTO school.students (first_name, last_name) VALUES ('firstName1', 'lastName1');
INSERT INTO school.students (first_name, last_name) VALUES ('firstName2', 'lastName2');
INSERT INTO school.students (first_name, last_name) VALUES ('firstName3', 'lastName3');
INSERT INTO school.students (first_name, last_name) VALUES ('firstName4', 'lastName4');
INSERT INTO school.students (first_name, last_name) VALUES ('firstName5', 'lastName5');
INSERT INTO school.students (first_name, last_name) VALUES ('firstName6', 'lastName6');
INSERT INTO school.students (first_name, last_name) VALUES ('firstName7', 'lastName7');
INSERT INTO school.students (first_name, last_name) VALUES ('firstName8', 'lastName8');
INSERT INTO school.students (first_name, last_name) VALUES ('firstName9', 'lastName9');
INSERT INTO school.students (first_name, last_name) VALUES ('firstName10', 'lastName10');
INSERT INTO school.students (first_name, last_name) VALUES ('firstName11', 'lastName11');
INSERT INTO school.student_to_course (student_id, course_id) VALUES (1,1);
INSERT INTO school.student_to_course (student_id, course_id) VALUES (2,1);
INSERT INTO school.student_to_course (student_id, course_id) VALUES (3,1);
